### ISSUE TITLE
Player name given not found

### ISSUE THREAD

**Issue by Moelanz** [Coffee-fueled-deadlines/osrs-hiscores#3]
When looking for a username in N hiscores it doesn't find the user

user = Hiscores('moelanz', 'N')

Error occurred: Player name given not found in account type provided.  Valid account types are, 'N' (Normal), 'IM' (Iron Man), 'UIM' (Ultimate Iron Man), 'HIC' (Hardcore Iron Man)

**Comment by Coffee-fueled-deadlines** [comment]
This particular library is no longer supported.  In general, OSRSBytes (https://github.com/Coffee-fueled-deadlines/OSRSBytes) is a more robust library.  However, while attempting this with the OSRS_Hiscores Library, I was unable to duplicate.

What version of Python are you running?
